# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(verbose_name='거래일시')),
                ('amount', models.IntegerField(verbose_name='거래금액')),
                ('balance', models.IntegerField(verbose_name='잔고')),
                ('transaction_by', models.CharField(max_length=200, verbose_name='거래소')),
            ],
            options={
                'verbose_name': '거래내역',
                'verbose_name_plural': '거래내역',
            },
        ),
    ]
