# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-date',), 'verbose_name': '거래내역', 'verbose_name_plural': '거래내역'},
        ),
    ]
